[workspace]

members = ["packages/y-octo", "packages/y-octo-util"]
resolver = "2"

[workspace.dependencies]
y-octo = { workspace = true, path = "packages/y-octo" }
y-octo-util = { workspace = true, path = "packages/y-octo-util" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[profile.fast-release]
inherits = "release"
codegen-units = 16
lto = false

[profile.profiling]
inherits = "fast-release"
debug = true

# [profile.release.package.y-octo-fuzz]
# debug = 1
