# Keep in sync with .editorconfig
format_strings      = true
group_imports       = "StdExternalCrate"
hard_tabs           = false
imports_granularity = "Crate"
max_width           = 120
tab_spaces          = 4
wrap_comments       = true
