[package]
authors = ["x1a0t <405028157@qq.com>"]
edition = "2021"
license = "MIT"
name    = "y-octo-utils"
version = "0.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }
phf       = { version = "0.11", features = ["macros"] }
y-octo    = { workspace = true }
yrs       = "=0.16.5"
