[package]
name = "y-octo-utils"
version = "0.0.1"
authors = ["x1a0t <405028157@qq.com>"]
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
yrs = "=0.16.5"
y-octo = { workspace = true }
